### ISSUE TITLE
Consider adding a license for this project

### ISSUE THREAD

**Issue by DreamOfIce** [xiaozhuai/GifEncoder#2]
这是一个非常不错的项目，但浏览代码时我注意到，这个repo目前没有任何许可证(License)。
这意味着严格意义上它不是开源的，任何人都没有将其进行修改乃至编译到自己的项目中进行分发的权利。
我相信这大概率不是您的初衷，所以可以考虑添加一个许可证吗？例如MIT？

**Comment by xiaozhuai** [comment]
@DreamOfIce 已添加许可证
