### ISSUE TITLE
Missing include 

### ISSUE THREAD

**Issue by pascalreinhold** [xiaozhuai/GifEncoder#4]
Hey,
 I tried to build the library but it did not compile with MinGW. I get an error message that `uint8_t` and `int16_t` in GifEncoder.h are not defined. One needs to include 'stdint.h'. 

Interestingly everything compiles when using MSVC.

**Comment by xiaozhuai** [comment]
@pascalreinhold Thank you for reporting this. Would you like to submit a pr?

**Comment by pascalreinhold** [comment]
pr is submitted
